"""add test1 column

Revision ID: 36faea8845c7
Revises: 42b0ef9b3a83
Create Date: 2025-11-27 20:23:19.826116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36faea8845c7'
down_revision: Union[str, Sequence[str], None] = '42b0ef9b3a83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('test1', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'test1')
    # ### end Alembic commands ###
